### ISSUE TITLE
Failed to get existing workspaces

### ISSUE THREAD

**Issue by BeenzSyed** [hashicorp/consul-terraform-sync#163]
### Describe the bug
I get the following error when running CTS: 
```
2021/01/07 17:07:49.432143 [ERR] (driver.terraform) error initializing workspace, skipping apply for 'demo'
2021/01/07 17:07:49.432326 [ERR] (cli) error running controller in Once mode: could not apply changes for task demo: error tf-init for 'demo':
Error: Failed to get existing workspaces: Get "https://localhost:8500/v1/kv/consul-terraform-sync/terraform-env:?keys=&separator=%2F": http: server gave HTTP response to HTTPS client
```
I ran Consul, then CTS (I got an error the first time I ran it) and when I re-ran CTS, I got the above error.

My sync-tasks/demo folder contains the following files (no state file has been created till yet):
main.tf, terraform.tfvars,terraform.tfvars.tmpl, variables.tf

### Versions
**Consul Terraform Sync**
```
 0.1.0-techpreview2 (d844653)
Compatible with Terraform >= 0.13.0, < 0.15
```

**Consul Version**
```
Consul v1.9.1
```

**Terraform Version**
```
terraform 0.14.4
```

### Configuration File(s)
```
log_level = "INFO"
port = 8558
syslog {}
buffer_period {
  enabled = true
  min = "5s"
  max = "20s"
}

consul {
  address = "localhost:8500"
}

driver "terraform" {
  log = false
  persist_log = false

  backend "consul" {
    scheme = "https"
  }

  required_providers {
    myprovider = {
      source = "PaloAltoNetworks/panos"
    }
  }
}

terraform_provider "panos" {
  alias = "panos1"
  hostname = xxxxx
  username=xxxxxxx
  api_key = xxxxxxxx
}

task {
  name = "demo"
  description = "This task dynamically creates a Dynamic Address Group"
  source = "github.com/PaloAltoNetworks/terraform-panos-dag-nia"
  providers = ["panos.panos1"]
  services = ["web"]
}
```

**Comment by findkim** [comment]
Thanks for taking time to submit a bug ticket! Stating that you ran into this error the first time execution with a clean setup is very helpful. The error you described is reproducible 👍.

The URL it errors on is peculiar to be missing the task name "demo" after the `consul-sync/terraform-env:` KV prefix. `https://localhost:8500/v1/kv/consul-terraform-sync/terraform-env:?keys=&separator=%2F` should be `https://localhost:8500/v1/kv/consul-terraform-sync/terraform-env:demo?keys=&separator=%2F`.

This leads me to think that the merging logic for the `driver.terraform.backend` block is not functioning correctly when another configuration is set -- in your case `scheme = "https"`.

**Comment by findkim** [comment]
Had some time to re-review this with more attention and realized I had overlooked the actual error 😅 
```
http: server gave HTTP response to HTTPS client
```

The missing workspace name is due to the existing `sync-tasks/demo/.terraform/environment` file and the logic added in #136 retries to create the workspace context within the Consul KV backend. However this logic stopped short [here](https://github.com/hashicorp/consul-terraform-sync/blob/v0.1.0-techpreview2/client/terraform_cli.go#L120) with the `https` mismatch. The Consul backend client attempts to communicate to the Consul agent with `https` but it seems the Consul you are running is not configured for TLS. I was able to reproduce this with CTS running with Consul in dev mode.

Apologies for writing example configuration code that does not run properly! I updated the docs hopefully to avoid others from running into this confusion! https://github.com/hashicorp/consul/pull/9547
