### ISSUE TITLE
Log HTTP requests

### ISSUE THREAD

**Issue by findkim** [hashicorp/consul-terraform-sync#332]
#### Description
Add middleware to log HTTP requests in a standardized format

#### Use Cases
It's useful to have the API server log all HTTP requests for debugging, auditing, and security compliance purposes.

**Comment by wilkermichael** [comment]
To satisfy more structured logging that can also be consumed by log processors for debugging, auditing and security compliance purposes, I propose that CTS logging be handled by the go-hclog library, rather than the go log package.

One of the limitations of the library is that it seems to only allow for local time logging, if this is an issue we may have to try and find a workaround in the future.
