### ISSUE TITLE
Prevent Plaintext Secrets in Log Output

### ISSUE THREAD

**Issue by picatz** [hashicorp/consul-terraform-sync#35]
Help prevent plaintext secrets from being logged by the NIA daemon. This may be through documenting support for official/non-leaking Terraform providers, with security warnings, or implementing a (configurable?) secret-scrubber for known secret strings/patterns in NIA log output.

**Comment by findkim** [comment]
https://github.com/hashicorp/consul-terraform-sync/pull/86 provider configs are no longer logged by CTS.
https://github.com/hashicorp/consul-terraform-sync/pull/181 set provider variable as sensitive should prevent any provider configuration from outputting within Terraform logs for 0.14+

**Comment by findkim** [comment]
Other approaches to this request:
* Documents suggestion to set input variables as `sensitive` for modules ([here](https://www.consul.io/docs/nia/terraform-modules#module-input-variables))
* Template module also suggests and provides example how to set it ([here](https://github.com/hashicorp/consul-terraform-sync-template-module/blob/main/variables.tf#L55-L58))


As for call-outs for leaky Terraform providers, I'm not sure there's an efficient way to identify them all since it's a per-case basis and it may be limited to a few resources within a provider. To work around this, operators could disable (disabled by default) the Terraform logs completely.
